### ISSUE TITLE
Heavy desync problem 

### ISSUE THREAD

**Issue by lyxuo** [cl52902/SaltyV2#1]
Hey, when I am using Salty there is a heavy desync problem cause by I think “clone_create” hook?
Please look into this, Thank you!

**Comment by cl52902** [comment]
This is an issue with the original source. Having it injected provides you with protection, but at the cost of most of the game being broken or unavailable. I am slowly working on redoing the hooks when I have time away from work. Properly patching the SyncTree is low on my list of things to do, but it will eventually get done.
